@startuml
caption Instances and Connectors in configuration SimpleLedArduino
component [digital_output2 : DigitalOutputArduino]<<PIM>>
component [digital_input2 : DigitalInputArduino]<<PIM>>
component [timer : TimerArduino]<<PSM>>
component [led : LedUC]<<PIM>>
component [led2 : LedUC]<<PIM>>
component [arduino : ArduinoArduino]<<PSM>>
component [buzzer : Buzzer]<<PIM>>
component [button2 : Button]<<PIM>>
component [digital_output : DigitalOutputArduino]<<PIM>>
component [digital_input : DigitalInputArduino]<<PIM>>
component [button : Button]<<PIM>>
component [digital_output3 : DigitalOutputArduino]<<PIM>>
component [simple_Led : SimpleLed]<<PIM>>
[simple_Led : SimpleLed] -(0- [led : LedUC] : Led => Led
[simple_Led : SimpleLed] -(0- [button : Button] : Button => Button
[digital_output2 : DigitalOutputArduino] -(0- [arduino : ArduinoArduino] : DigitalIO => DigitalIO
[digital_output : DigitalOutputArduino] -(0- [arduino : ArduinoArduino] : DigitalIO => DigitalIO
[digital_input : DigitalInputArduino] -(0- [arduino : ArduinoArduino] : DigitalIO => DigitalIO
[buzzer : Buzzer] -(0- [timer : TimerArduino] : timer => timer
[digital_input2 : DigitalInputArduino] -(0- [arduino : ArduinoArduino] : DigitalIO => DigitalIO
[led2 : LedUC] -(0- [digital_output3 : DigitalOutputArduino] : DigitalOutput => DigitalOutput
[simple_Led : SimpleLed] -(0- [led2 : LedUC] : Led2 => Led
[digital_output3 : DigitalOutputArduino] -(0- [arduino : ArduinoArduino] : DigitalIO => DigitalIO
[led : LedUC] -(0- [digital_output : DigitalOutputArduino] : DigitalOutput => DigitalOutput
[simple_Led : SimpleLed] -(0- [timer : TimerArduino] : timer => timer
[button2 : Button] -(0- [digital_input2 : DigitalInputArduino] : DigitalInput => DigitalInput
[buzzer : Buzzer] -(0- [digital_output2 : DigitalOutputArduino] : DigitalOutput => DigitalOutput
[simple_Led : SimpleLed] -(0- [buzzer : Buzzer] : Buzzer => Buzzer
[button : Button] -(0- [digital_input : DigitalInputArduino] : DigitalInput => DigitalInput
[simple_Led : SimpleLed] -(0- [button2 : Button] : Button2 => Button
@enduml